/* Main.c file generated by New Project wizard

5. Utilize dois botões para acionar os 8 leds de uma barra gráfica:
• No início do programa, devem ser acionados os primeiros 4 LEDS e os demais desligados.
• Cada vez que o botão 1 for pressionado, um LED deve ser aceso para encher a barra.
• Cada vez que o botão 2 for pressionado, um LED deve ser apagado para esvaziar a barra

 */

#include <p18f4450.h>
#include <delays.h>

#pragma config FOSC = HS
#pragma config WDT = OFF
#pragma config MCLRE = OFF

#define bt_mais		PORTAbits.RA0
#define bt_menos	PORTAbits.RA1


int estadoAnteriorBTMais = 1;
int estadoAnteriorBTMenos = 1;
int flag_bt_mais = 0;
int flag_bt_menos = 0;
int contador = 4;
int minimo = 1;
int maximo = 8;


void delay_ms(unsigned int tempo){
   while(tempo > 0){
      Delay100TCYx(10);
      tempo--;
      }
   }
   
void delay_bounce(){
   delay_ms(30);
   }
   
void ler_bt_mais(){
   if(bt_mais == 1 && !estadoAnteriorBTMais == 1){
      flag_bt_mais = 1;
   }
   estadoAnteriorBTMais = bt_mais;
}
  
void ler_bt_menos(){
   if(bt_menos == 1 && !estadoAnteriorBTMenos == 1){
      flag_bt_menos = 1;
   }
   estadoAnteriorBTMenos = bt_menos;
}

void atualiza_contador(){
   if (flag_bt_mais == 1){
      flag_bt_mais = 0;
      if (contador < maximo){
	 contador ++; 
      }
      else{
	 contador = maximo;
      }
   }
   
   if (flag_bt_menos == 1){
      flag_bt_menos = 0;
      if (contador > minimo ){
	 contador --; 
      }
      else{
	 contador = minimo;
      }
   }
}

void atualiza_leds(){
   switch(contador){
      case 1:
	 PORTB = 0b00000001;
	 break;
      case 2:
	 PORTB = 0b00000011;
	 break;
      case 3:
	 PORTB = 0b00000111;
	 break;
      case 4:
	 PORTB = 0b00001111;
	 break;
      case 5:
	 PORTB = 0b00011111;
	 break;
      case 6:
	 PORTB = 0b00111111;
	 break;
      case 7:
	 PORTB = 0b01111111;
	 break;
      case 8:
	 PORTB = 0b11111111;
	 break;
   }
}


void main(){ 
   PORTA = 0x00; LATA = 0x00; TRISA = 0x03;
   PORTB = 0x00; LATB = 0x00; TRISB = 0x00;
   ADCON1 = 0x0F;
   LATB = 0x0F;
   
   while (1){
      ler_bt_mais();
      ler_bt_menos();
      atualiza_contador();
      atualiza_leds();      
      delay_bounce();
   }
 }
